#include "ExtendedDataTypes.idl" // openrtm

module primitive_motion_level_msgs
{
  typedef double DblSequence6[6];
  typedef sequence<double> DblSequence;
  typedef sequence<DblSequence6> DblSequence6Sequence;

  struct PrimitiveStateIdl
  {
    string name;
    string parentLinkName;
    RTC::Pose3D localPose;

    // world frame
    double time; // interpolation time
    RTC::Pose3D pose;
    DblSequence6 wrench;
    DblSequence6 poseFollowGain;// pose local frame
    DblSequence6 wrenchFollowGain;// pose local frame

    // local frame (if isGlobal=false). world frame (if isGlobal=true).
    boolean isPoseCGlobal;
    DblSequence6Sequence poseC; //pose の frameからのerror の制約
    DblSequence poseld;
    DblSequence  poseud;
    boolean isWrenchCGlobal;
    DblSequence6Sequence wrenchC; //wrench の制約
    DblSequence wrenchld;
    DblSequence wrenchud;

    // local frame
    DblSequence6 actWrench; // Position control only
    DblSequence6 M;
    DblSequence6 D;
    DblSequence6 K;

    // 支持脚かどうか
    boolean supportCOM;
  };

  struct TimedPrimitiveStateSeq
  {
    RTC::Time tm;
    sequence<PrimitiveStateIdl> data;
  };
};
