#include "ExtendedDataTypes.idl" // openrtm

module WholeBodyMasterSlaveChoreonoidIdl
{
  enum ContactState {
    CONTACT,
    AIR
  };

  enum ConstraintType {
    SIX_AXIS,
    TRANSLATION_ONLY,
    ROTATION_ONLY,
    FREE
  };

  struct EndEffectorState
  {
    string name;
    string parentLinkName;
    RTC::Pose3D localPose;
    string forceSensorName;
    RTC::Pose3D pose;
    sequence<double> wrench;
  };

  struct TimedEndEffectorStateSeq
  {
    RTC::Time tm;
    sequence<EndEffectorState> data;
  };
};
