#include "ExtendedDataTypes.idl" // openrtm

module WholeBodyMasterSlaveChoreonoidIdl
{
  struct EndEffectorState
  {
    enum Type {
      FIX,
      FLOAT,
      FLOAT_TRANSLATION_ONLY,
      FLOAT_ROTATION_ONLY,
      FREE
    };

    string name;
    string parentLinkName;
    RTC::Pose3D localPose;
    string forceSensorName;
    RTC::Pose3D pose;
    sequence<double> wrench;
  };

  struct TimedEndEffectorStateSeq
  {
    RTC::Time tm;
    sequence<EndEffectorState> data;
  };
};
