/**
 * @file PrimitiveMotionLevelControllerService.idl
 * @brief Services for the PrimitiveMotionLevelController interface
 */
#include "ExtendedDataTypes.idl" // openrtm
module whole_body_master_slave_choreonoid
{
  interface PrimitiveMotionLevelControllerService
  {
    struct PrimitiveMotionLevelControllerParam
    {
      long debugLevel;
    };
    void setParams(in PrimitiveMotionLevelControllerParam i_param);
    void getParams(out PrimitiveMotionLevelControllerParam i_param);

    boolean startControl();
    boolean stopControl();
  };
};
