/**
 * @file WholeBodyMasterSlaveService.idl
 * @brief Services for the WholeBodyMasterSlave interface
 */
#include "PrimitiveState.idl"
#include "ExtendedDataTypes.idl" // openrtm
module WholeBodyMasterSlaveChoreonoidIdl
{
  interface PrimitiveMotionLevelControllerService
  {
    typedef sequence<double, 2> DblSequence2;
    typedef sequence<double, 3> DblSequence3;
    typedef sequence<double, 4> DblSequence4;
    typedef sequence<string> StrSequence;

    struct frame
    {
      string parentLinkName;
      RTC::Pose3D localPose;
    };

    struct PrimitiveCommand
    {
      RTC::Time tm;
      TimedPrimitiveStateSeq command;
      frame fixedFrame;
    };

    struct PrimitiveMotionLevelControllerParam
    {
      string hoge;
    };
    void setParams(in PrimitiveMotionLevelControllerParam i_param);
    void getParams(out PrimitiveMotionLevelControllerParam i_param);

    boolean startControl();
    boolean stopControl();
  };
};
