/**
 * @file PrimitiveMotionLevelControllerService.idl
 * @brief Services for the PrimitiveMotionLevelController interface
 */
#include "PrimitiveState.idl"
#include "ExtendedDataTypes.idl" // openrtm
module WholeBodyMasterSlaveChoreonoidIdl
{
  interface PrimitiveMotionLevelControllerService
  {
    struct PrimitiveMotionLevelControllerParam
    {
      string hoge;
    };
    void setParams(in PrimitiveMotionLevelControllerParam i_param);
    void getParams(out PrimitiveMotionLevelControllerParam i_param);

    boolean startControl();
    boolean stopControl();
  };
};
