/**
 * @file PrimitiveMotionLevelCOMControllerService.idl
 * @brief Services for the PrimitiveMotionLevelCOMController interface
 */
#include "PrimitiveStateIdl.idl"
#include "ExtendedDataTypes.idl" // openrtm
module whole_body_master_slave_choreonoid
{
  interface PrimitiveMotionLevelCOMControllerService
  {
    struct PrimitiveMotionLevelCOMControllerParam
    {
      string hoge;
    };
    void setParams(in PrimitiveMotionLevelCOMControllerParam i_param);
    void getParams(out PrimitiveMotionLevelCOMControllerParam i_param);

    boolean startControl();
    boolean stopControl();
  };
};
